# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a384fdd560d1aa5e12af9dc4cc1d1054b8785be9bf32de1e81000525917ddb2ae7c86934ae9bd66910cc4ea4d5f829f81590fe2c51eeac4acb8810992f395360

test:
  secret_key_base: 896f242e548bf8a2a4c1968d48c3d51ba9048f0f623ecac6c71402b790c49888ff42b56578b4f65e2a7aee2578a602653dcb1b11ea22036e557bd876d524e003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
